<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fortunacoin</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Fortunacoin (FTC)</h1>
        <nav>
            <ul>
                <li><a href="#about">Acerca de</a></li>
                <li><a href="#features">Características</a></li>
                <li><a href="#roadmap">Roadmap</a></li>
                <li><a href="#team">Equipo</a></li>
                <li><a href="#contact">Contacto</a></li>
            </ul>
        </nav>
    </header>
    <section id="about">
        <h2>Acerca de Fortunacoin</h2>
        <p>Fortunacoin es una criptomoneda descentralizada diseñada para proporcionar transacciones rápidas y seguras con tarifas mínimas. Nuestro objetivo es construir una comunidad fuerte y participativa.</p>
    </section>
    <section id="features">
        <h2>Características</h2>
        <ul>
            <li>Transacciones rápidas y económicas</li>
            <li>Seguridad y descentralización</li>
            <li>Interfaz de usuario amigable</li>
            <li>Staking y recompensas</li>
        </ul>
    </section>
    <section id="roadmap">
        <h2>Roadmap</h2>
        <ol>
            <li>Desarrollo inicial del token</li>
            <li>Lanzamiento de la wallet</li>
            <li>Implementación del exchange</li>
            <li>Expansión de funcionalidades</li>
        </ol>
    </section>
    <section id="team">
        <h2>Equipo</h2>
        <p>Conoce al equipo detrás de Fortunacoin.</p>
    </section>
    <section id="contact">
        <h2>Contacto</h2>
        <p>Para más información, contáctanos en <a href="mailto:info@fortunacoin.com">info@fortunacoin.com</a>.</p>
    </section>
    <footer>
        <p>&copy; 2024 Fortunacoin. Todos los derechos reservados.</p>
    </footer>
</body>
</html>
